Repository beetlestance/Aphid, pull requests merged in 2022-07, with the labels that each got.

#66 compose runtime added for compose lifecycle extension for snapshot state
  common-compose/build.gradle.kts
  feature-chat/src/main/java/com/beetlestance/aphid/feature/chat/Chat.kt
  feature-explore/src/main/java/com/beetlestance/aphid/feature/explore/Explore.kt
  feature-profile/src/main/java/com/beetlestance/aphid/feature/profile/Profile.kt
  gradle/libs.versions.toml
Labels: dependencies

#67 Revisit current code structure
  app/src/main/java/com/beetlestance/aphid/AphidHome.kt
  common-compose/src/main/java/com/beetlestance/aphid/common/compose/DominantColor.kt
  common-compose/src/main/java/com/beetlestance/aphid/common/compose/bottomnavigation/BottomNavigation.kt
  common-compose/src/main/java/com/beetlestance/aphid/common/compose/extensions/Padding.kt
  common-compose/src/main/java/com/beetlestance/aphid/common/compose/theme/Color.kt
  common-compose/src/main/java/com/beetlestance/aphid/common/compose/theme/shapes/CutOutShape.kt
  data-android/schemas/com.beetlestance.aphid.data.android.AphidRoomDatabase/1.json
  data/src/main/java/com/beetlestance/aphid/data/entities/Recipe.kt
  data/src/main/java/com/beetlestance/aphid/data/mapper/RecipeInformationToRecipe.kt
  feature-explore/src/main/java/com/beetlestance/aphid/feature/explore/Explore.kt
  feature-explore/src/main/java/com/beetlestance/aphid/feature/explore/ExploreBreakfast.kt
  feature-profile/src/main/java/com/beetlestance/aphid/feature/profile/Profile.kt
  gradle/libs.versions.toml
Labels: enhancement, refactor

#69 Disable configuration cache in CI
  .github/ci-gradle.properties
Labels: bug
